disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Eonloop"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = ""
  [params.author]
    image="IMG_0542.JPG"
    name = "Ian Jones"
    links = [ { bluesky = "https://bsky.app/profile/eonloop.bsky.social" }, { github = "https://github.com/Eonflip" }, { linkedin = "https://www.linkedin.com/in/ianj1993/" } ]
    headline = "Tech, Books, Nature"

